<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="AWSSDK.Core" Version="3.7.400.10" />
		<PackageReference Include="AWSSDK.S3" Version="3.7.402.1" />
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.64" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.8" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NLog" Version="5.3.3" />
		<PackageReference Include="NLog.Extensions.Logging" Version="5.3.12" />
		<PackageReference Include="Npgsql" Version="8.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
		<PackageReference Include="Otp.NET" Version="1.4.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.24.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
	</ItemGroup>
	
</Project>
